# Generated by Django 4.2.2 on 2025-04-21 06:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('PhoneNumberField', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BD')),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('cover_image', models.ImageField(upload_to='profile/')),
                ('date_of_birth', models.DateField()),
                ('degree', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Personal Info',
                'verbose_name_plural': 'Personal Info',
            },
        ),
    ]
