# Generated by Django 4.2.2 on 2025-04-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='PhoneNumberField',
            new_name='phone',
        ),
    ]
