# Generated by Django 4.2.2 on 2025-04-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_rename_phonenumberfield_personalinfo_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=250)),
                ('profile_summary', models.TextField(max_length=500)),
                ('photo', models.ImageField(upload_to='profile/')),
            ],
        ),
    ]
