# Generated by Django 4.2.2 on 2025-04-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
    ]
