# Generated by Django 4.2.2 on 2025-04-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_alter_about_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile_summary2',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='profile_summary',
            field=models.TextField(max_length=250),
        ),
    ]
