# Generated by Django 4.2.2 on 2025-04-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_about_profile_summary2_alter_about_profile_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_summary2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
