# Generated by Django 4.2.2 on 2025-04-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_skill_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
