# Generated by Django 4.2.2 on 2025-05-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
