# Generated by Django 4.2.2 on 2025-05-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0014_alter_description_contact_alter_description_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
