# Generated by Django 4.2.2 on 2025-04-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=80)),
                ('institute', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
