# Generated by Django 4.2.2 on 2025-04-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
