# Generated by Django 4.2.2 on 2025-04-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_education_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='running',
        ),
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
