# Generated by Django 4.2.2 on 2025-04-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0004_professionalexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexperience',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
