# Generated by Django 4.2.2 on 2025-04-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0006_certifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certifications',
            new_name='Certification',
        ),
    ]
