# Generated by Django 4.2.2 on 2025-05-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0009_certification_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='file',
        ),
    ]
