# Generated by Django 4.2.2 on 2025-04-25 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('bio', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BD')),
                ('dob', models.DateField(blank=True, null=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='client/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='client/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clientinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
