# Generated by Django 4.2.2 on 2025-05-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0004_alter_service_icon_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
