# Generated by Django 4.2.2 on 2025-05-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
